spring:
  datasource:
    url: jdbc:h2:mem:terminumfrage;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080
app:
  jwt:
    secret: supersecretkeysupersecretkeysupersecretkey
    expiration: 3600
